project_id = "ahruzugnghcqkonygydo"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.paypal-create-subscription]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false